apiVersion: v1
kind: Template
labels:
  template: bayesian-pgweb
metadata:
  name: bayesian-pgweb
  annotations:
    description: Bayesian pgweb
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: bayesian-pgweb
    name: bayesian-pgweb
  spec:
    replicas: 1
    selector:
      service: bayesian-pgweb
    template:
      metadata:
        labels:
          service: bayesian-pgweb
      spec:
        containers:
        - env:
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: bayesian-pgweb
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 5
          ports:
          - containerPort: 8081
            protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: bayesian-pgweb
    name: bayesian-pgweb
  spec:
    ports:
    - name: "8081"
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      service: bayesian-pgweb

parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "docker.io"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "sosedoff/pgweb"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag
